service: CommonFeePlan-get-paid-history

plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: api.borderless.mym.works
    basePath: 'paidhistory'
    stage: ${self:provider.stage}

provider:
  name: aws
  runtime: python3.8

  stage: prd
  region: ap-northeast-1

  memorySize: 128

  iamRoleStatements:
    - Effect: 'Allow'
      Resource:
        - 'arn:aws:dynamodb:ap-northeast-1:778289792916:table/borderless-common-fee'
      Action:
        - dynamodb:Query

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /{house_name}/{tenant_name}
          method: get
          cors: 
            origins: 
              - https://commonfee.borderless.mym.works
              - https://lemon-stone-0093d5e00-*.eastasia.azurestaticapps.net
              - http://localhost:3000
          private: true
