sls-python-requirements:
			yarn add serverless-python-requirements

local-invoke:
			sls invoke local --function main --aws-profile mym-lab --path ./test-data/insert.json

deploy: 
			sls deploy --aws-profile mym-lab
